title: Test Git 1
author: Yhoedge
email: yohedge@yahoo.fr
description: > # this means to ignore newlines until "baseurl:"
Bla bla bla bla blza

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
